### PR TITLE
[FEATURE] New TV Show example config

### PR DESCRIPTION
**Pull request by jmbannon**

### CODE REVIEW

**Comment by sunnyd24** [comment]
@jmbannon Just a note, this is not a TV Show example but a Music Video example with rick roll.

**Comment by jmbannon** [comment]
@sunnyd24 this commit created this TV show example https://github.com/jmbannon/ytdl-sub/blob/master/examples/tv_show_config.yaml#L7

**Comment by sunnyd24** [comment]
@jmbannon I am referring to the TV Show subscriptions example yaml file: 
https://github.com/jmbannon/ytdl-sub/tree/master/examples/tv_show_subscriptions.yaml

**Comment by jmbannon** [comment]
It's his channel, which is no different than any other channel as a TV show 😊

**Pull request merged**
